DROP TABLE IF EXISTS USER_DETAILS;  
CREATE TABLE USER_DETAILS (  
ID INT AUTO_INCREMENT  PRIMARY KEY,
CUSTOMER_ID INT NOT NULL,
EMAIL VARCHAR(50) NOT NULL,  
PHONE_NUMBER VARCHAR(10) NOT NULL  
);

DROP TABLE IF EXISTS BANK_DETAILS;  
CREATE TABLE BANK_DETAILS (  
BANK_ID INT AUTO_INCREMENT  PRIMARY KEY,
CUSTOMER_ID INT NOT NULL,
ACCOUNT_NUMBER VARCHAR(26) NOT NULL
);

